### PR TITLE
Bugfixes (from PE dry run)

### LINKED ISSUE #137: [PE-D] Did not show the tip symbol at legend table
Is this the bug? Should show the tip symbol.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: Exeexe93/ped#6

### LINKED ISSUE #142: [PE-D] 1.1 Confusion for meaing for "..." in Legend
What is the meaning of 0 times? Is it a typo error? As the example given is about 3 goals, I suggest you could change to 3 times.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Exeexe93/ped#1

### LINKED ISSUE #147: [PE-D] Find command doesn't support finding a substring
-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Guofeng-Tang/ped#1

### LINKED ISSUE #149: [PE-D] Missing Icon for Tags in UG
-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: joshlay96/ped#8

### LINKED ISSUE #152: [PE-D] String formatting of ingredients
Can consider formatting capitalisation of the ingredients

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: joshlay96/ped#5

### LINKED ISSUE #155: [PE-D] Allowing users to unfavourite even if item is not marked as favourite
If its meant to be so, maybe you would like to put it as a note in your UG?

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: joshlay96/ped#2

### LINKED ISSUE #156: [PE-D] Bug when using Favourites
Throws an exception when deleteing multiple receipes and valid indexed receipes are not deleted. 

Eg:Assuming you have 10 items in the list and you execute "delete 1,10,100", and nothing is deleted. 

However, even though an exception is thrown when favouriting multiple receies, the valid indexed receipes are still marked as favourite. 

Eg: Assuming you have 10 items in the list and you execute  "favourite 1,10,100", object in index 1 and 10 are marked as favourite even though 100 is an invalid index. 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: joshlay96/ped#1

### PR DESCRIPTION
**Pull request by pekchinsiongbrian**
Please refer to `Linked Issues` to see which issues this PR addresses.

### CODE REVIEW

File: src/main/java/seedu/recipe/logic/commands/FavouriteCommand.java [hunk 1]
```diff
@@ -36,31 +39,66 @@ public FavouriteCommand(Index[] targetIndex) {
     public CommandResult execute(Model model) throws CommandException {
         requireNonNull(model);
         List<Recipe> lastShownList = model.getFilteredRecipeList();
-        StringBuilder sb = new StringBuilder().append("Added ");
+        List<String> successfulFavouritesList = new ArrayList<>();
```
Comment (tharshita) [inline src/main/java/seedu/recipe/logic/commands/FavouriteCommand.java:42]: perhaps the naming could be slightly more different between successfulFavouritesList and alreadyFavouritesList or javadoc comments could be added to clarify, because when I first read it I didn't really get the difference between the two (but maybe it's just me)

File: src/test/java/seedu/recipe/model/recipe/NameContainsKeywordsPredicateTest.java [hunk 2]
```diff
@@ -34,41 +38,44 @@ public void equals() {
...
         assertFalse(predicate.test(new RecipeBuilder().withName("Alice").build()));
 
         // Non-matching keyword
-        predicate = new NameContainsKeywordsPredicate(Arrays.asList("Carol"));
+        predicate = new NameContainsKeywordsPredicate(true, "Carol");
         assertFalse(predicate.test(new RecipeBuilder().withName("Alice Bob").build()));
 
         // Keywords match time and step, but does not match name
-        predicate = new NameContainsKeywordsPredicate(Arrays.asList("12345", "alice@email.com", "Main", "Street"));
+        predicate = new NameContainsKeywordsPredicate(true, "12345 alice@email.com Main Street");
```
Comment (tharshita) [inline src/test/java/seedu/recipe/model/recipe/NameContainsKeywordsPredicateTest.java:78]: thanks for the hard work!

File: docs/UserGuide.adoc [hunk 3]
```diff
@@ -132,10 +132,12 @@ From sections 6 to 11, the following notations may be used.
 |Notation |Meaning
 
 |[ ] |Necessary field
-|< > |Optional field. e.g. `n/NAME <g/GOAL>` can be used as `n/Spicy Chicken g/Bulk like the Hulk` or as `n/Spicy Chicken`
+|< > |Optional field. e.g. `n/NAME <s/STEP>` can be used as `n/Spicy Chicken s/Step 1` or just `n/Spicy Chicken`
 |[ < > ] |At least one of the optional fields is necessary
-|… | One or more of this same field can be added. e.g. `<g/GOAL>...` can be used as `{nbsp}` (i.e. 0 times), `g/Bulk like the Hulk`, `g/Wholesome Wholemeals`, `g/Herbivore` etc.
-|image::Tip.png[] | Tip
+|… | One or more of this same field can be added. e.g. if the command specifies `<ip/PROTEIN>...`, you may either leave
+the field empty, or you may specify ≥1 protein ingredients.
```
Comment (beatricetay) [inline docs/UserGuide.adoc:139]: I think writing out 'more than one' would be better than >= 1!

File: docs/UserGuide.adoc [hunk 4]
```diff
@@ -132,10 +132,12 @@ From sections 6 to 11, the following notations may be used.
 |Notation |Meaning
 
 |[ ] |Necessary field
-|< > |Optional field. e.g. `n/NAME <g/GOAL>` can be used as `n/Spicy Chicken g/Bulk like the Hulk` or as `n/Spicy Chicken`
+|< > |Optional field. e.g. `n/NAME <s/STEP>` can be used as `n/Spicy Chicken s/Step 1` or just `n/Spicy Chicken`
```
Comment (beatricetay) [inline docs/UserGuide.adoc:136]: I think we should put the 'NAME' and 'STEP' in lower case letters to follow the same format we used in the UG later

**Review by beatricetay — COMMENTED** [review]
Thanks Brian! :)

File: docs/UserGuide.adoc (hunk 3 above)
Comment (tharshita) [reply docs/UserGuide.adoc:139]: how about one or more? HAHA

File: src/main/java/seedu/recipe/logic/commands/FavouriteCommand.java [hunk 5]
```diff
@@ -36,31 +39,66 @@ public FavouriteCommand(Index[] targetIndex) {
...
-            if (i == targetIndex.length - 1 && targetIndex.length != 1) {
-                sb.append(" and ");
-            }
-            sb.append(recipeToFavourite.getName().toString());
-            if (i < targetIndex.length - 2) {
-                sb.append(", ");
+        for (Index index : targetIndex) {
+            Recipe recipeToFavourite = lastShownList.get(index.getZeroBased());
+            if (!recipeToFavourite.isFavourite()) {
+                model.favouriteRecipe(recipeToFavourite);
```
Comment (beatricetay) [inline src/main/java/seedu/recipe/logic/commands/FavouriteCommand.java:52]: Hey Brian, I was wondering whether we could format the favourite command (and the unfavourite command) to be similar to the edit command, where it searches for the Recipe to favourite, creates a new Recipe object with favourite = true, and calls model.setRecipe instead.
Currently, the model.favouriteRecipe method would create a new Recipe in the UniqueRecipeList class, and im thinking that it might not be good to create a new Recipe in this class.

Comment (pekchinsiongbrian) [reply src/main/java/seedu/recipe/logic/commands/FavouriteCommand.java:52]: Thanks for pointing this out! I did this ages ago before I could appreciate the usage of EditRecipeDescriptor. Fixed in latest PR.

File: docs/UserGuide.adoc (hunk 3 above)
Comment (pekchinsiongbrian) [reply docs/UserGuide.adoc:139]: Fixed in latest PR!

File: src/main/java/seedu/recipe/logic/commands/FavouriteCommand.java (hunk 1 above)
Comment (pekchinsiongbrian) [reply src/main/java/seedu/recipe/logic/commands/FavouriteCommand.java:42]: Fixed in latest PR! I hope the new naming makes more sense (see latest PR)
