### PR TITLE
Fixed bug - Auto updates piechart with every cooked command

### LINKED ISSUE #132: pie chart not updating unless restarting

### LINKED ISSUE #139: [PE-D] Pie chart not synchronise with the cooked food for the goals
The Ui for the pie chart does not synchronise with the label of the goals for the cooked food. I have 7 wholesome
wholemeal and it should take half of the piechart instead of only take up 1/4 of the chart. Furthermore, the bulk like the hulk should be lesser than the wholesome wholemeal, but it takes 1/2 of the piechart.

It will confuse the user.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Exeexe93/ped#4

### PR DESCRIPTION
**Pull request by tharshita**

### CODE REVIEW

File: src/main/java/seedu/recipe/model/Model.java [hunk 1]
```diff
@@ -184,6 +184,12 @@
     /** Returns an unmodifiable view of the filtered record list */
     ObservableList<Record> getFilteredRecordList();
 
+    /**
+     * updates goal tally every time a record is added
+     * @param record
```
Comment (beatricetay) [inline src/main/java/seedu/recipe/model/Model.java:189]: I think it might be better to standardize the JavaDoc convention and follow AB3's format, which refers to parameters as {@code record} instead of @param record

File: src/main/java/seedu/recipe/model/cooked/UniqueRecordList.java [hunk 2]
```diff
@@ -140,16 +144,49 @@ private boolean recordsAreUnique(List<Record> records) {
...
+        List<Goal> currGoals = new ArrayList<Goal>();
+        currGoals.addAll(record.getGoals());
+        for (Goal currGoal: currGoals) {
+            String goalName = currGoal.goalName;
+            int currCount = 0;
+            switch(goalName) {
+
+            case "Herbivore":
+                currCount = internalGoalsList.get(0);
+                internalGoalsList.set(0, currCount + 1);
```
Comment (beatricetay) [inline src/main/java/seedu/recipe/model/cooked/UniqueRecordList.java:176]: I think it would be good to add that 0, 1 and 2 refers to "herbivore", "bulk like the hulk" and "wholesome wholemeal" somewhere in the javadoc

**Review by beatricetay — COMMENTED** [review]
Thanks for the hard work!!
